//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratespiel.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ratespiel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die v. 1.0.0_b4 (08.08.2017)
        ///NEU:
        ///* Sollte man bei dem Einsatz als Vorzeichen ein +,-,*, oder / Zeichen eingeben werden
        ///  diese nun entfernt.
        ///* Es gibt nun einen Mehrspieler modus wo der 2. Spieler die Zahl von dem 1. Spieler
        ///  erraten muss. Es sind alle Ganzzahlen bis zu 2 147 483 647 möglich.
        ///* Es gibt nun eine Highscore Liste. Diese wird in den AppData Ordner der Anwendung
        ///  gespeichert. Speicherort: 
        ///  %appdata%\Spielsücht\Spielsücht\Highscore_Spiel[Nummer des Spiel].csv
        ///  * Jedes Spiel hat eine ei [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obwohl dieses Programm ein OpenSource Programm
        ///ist bitte ich darum dises nicht unter dem eigenen
        ///Namen zu veröffentlichen. Solltest du dennoch das
        ///Programm veröffentlichen bitte ich darum darauf
        ///hinzuweisen das nicht du das Programm erstellt hast.
        ///Außerdem bitte ich darum diesen hinweis nicht zu
        ///entfernen und die Über Form nicht zu verändern.
        ///Hälst du dich an diese kleine bitte kannst du das
        ///Spiel so verändern wie du es gerne möchtest.
        ///Danke
        ///Aaron H. ähnelt.
        /// </summary>
        public static string Hinweis {
            get {
                return ResourceManager.GetString("Hinweis", resourceCulture);
            }
        }
    }
}
